name: Link Check
on:
  workflow_call: {}
  workflow_dispatch: {}
jobs:
  check-links:
    name: Link Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: Run lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: "--verbose --no-progress --cache --max-cache-age 1d ."
          fail: true